import "../globals.css";
import React from "react";
import type { Metadata } from "next";
import { Oswald, Urbanist } from "next/font/google";
const oswald = Oswald({ subsets: ["latin"] });
const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function AuthenticateLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${oswald.className} ${urbanist.className}`}
      >
        {children}
      </body>
    </html>
  );
}
