import type { Metadata } from "next";
import { Oswald, Urbanist } from "next/font/google";
import "../globals.css";
const oswald = Oswald({ subsets: ["latin"] });
const urbanist = Urbanist({ subsets: ["latin"] });
import { Header, Footer } from "@/components";
import { StoreProvider } from "@/store/StoreProvider";

export const metadata: Metadata = {
  title: "Online Shopping for Men, Women and Kids Fashion & Lifestyle - Nexly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body
          suppressHydrationWarning={true}
          className={`${oswald.className} ${urbanist.className}`}
        >
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </StoreProvider>
  );
}
